# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Carrie C Myers - Virtual Assistant
tagline:          
description:      
url:              cc115915.github.io
baseurl:          /va
domain:           cc115915.github.io

author:
  name:           Carrie Myers
  url:            

#paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           

