# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Carrie C Myers - Virtual Assistant
tagline:          
description:      
url:              cc115915.github.io/va
baseurl:          /

author:
  name:           
  url:            

#paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           
