# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Carrie C Myers - Virtual Assistant
tagline:          
description:      
url:              carriecmyers.net
baseurl:          /va
domain:           carriecmyers.net

author:
  name:           Carrie Myers
  url:            

#paginate:         5

# Custom vars
version:          2.1.0


